AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'app/helpers/flashes_helper.rb'
    - 'vendor/**/*'

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**.*'

Style/ParallelAssignment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/LineLength:
  Max: 85
