AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'app/helpers/flashes_helper.rb'
Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**.*'
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Metrics/LineLength:
  Max: 85
