AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'spec/**/*'
    - 'app/helpers/flashes_helper.rb'
    - 'vendor/**/*'

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/LineLength:
  Max: 85

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'app/models/github_api/response_object_converter.rb'

Security/MarshalLoad:
  Exclude:
    - 'app/models/portfolio.rb'

Style/Documentation:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/helpers/**.*'

Style/ParallelAssignment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
